spring:
  application:
    name: item-service
    
  rabbitmq:
    host: 192.168.92.135
    port: 5672
    username: admin
    password: admin   
    
#server:
#  port: 8100
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
---
spring:
  profiles: item1
  
server:
  port: 8100
---
spring:
  profiles: item2

server:
  port: 8002 
  

      